# Generated by Django 5.0.6 on 2024-06-15 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_customuser_is_auctioner_auction_bidstoauction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
