# Generated by Django 5.0.6 on 2024-06-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='max_bids',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
