# Generated by Django 5.0.6 on 2024-06-17 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auction_max_bids_alter_auction_created_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bidstoauction',
            unique_together={('auction', 'bidder')},
        ),
    ]
